import type { ComponentProtocolDefinition } from '../types';

export const customHtmlProtocol: ComponentProtocolDefinition = {
  type: 'customHtml',
  title: '自定义HTML组件',
  summary: '通过 iframe 沙箱渲染用户自定义 HTML/CSS/JS，支持 ScadaBridge 实时数据桥接与第三方库加载。',
  usage: [
    '适用于内置物料无法满足的高级可视化场景，如自定义仪表盘、D3 拓扑图等。',
    '用户 JS 代码通过 ScadaBridge SDK 访问实时变量与数据库，禁止直接操作 parent 页面 DOM。',
    '可上传 ECharts、D3.js 等第三方库离线包，通过 libraryAssetIds 引用加载。',
    '支持透明背景，可与其他组件叠加形成复合可视化层。',
  ],
  supportedEvents: [
    {
      key: 'onLoad',
      label: 'iframe 加载完成',
      summary: 'iframe 内容加载完毕后执行，可在此初始化 ScadaBridge 订阅。',
      scope: 'component',
      sharedWithAi: true,
    },
  ],
  supportedMethods: [
    {
      name: 'ScadaBridge.readTag',
      summary: '读取指定变量点位的当前值。',
      signature: 'ScadaBridge.readTag(tagName: string): Promise<{ value: any, timestamp: number }>',
      example: "const data = await ScadaBridge.readTag('temperature');",
    },
    {
      name: 'ScadaBridge.writeTag',
      summary: '向指定变量点位写入值（需要 RW 权限）。',
      signature: 'ScadaBridge.writeTag(tagName: string, value: any): Promise<{ success: boolean }>',
      example: "await ScadaBridge.writeTag('setpoint', 75.5);",
    },
    {
      name: 'ScadaBridge.subscribe',
      summary: '订阅变量值变化，返回取消订阅函数。',
      signature: 'ScadaBridge.subscribe(tagName: string, callback: (data: { value: any, timestamp: number }) => void): () => void',
      example: "const unsub = ScadaBridge.subscribe('pressure', d => console.log(d.value));",
    },
    {
      name: 'ScadaBridge.readVar',
      summary: '读取当前页面运行时变量，返回完整变量对象，包含 value、previousValue、quality、valueTs、扩展字段等。',
      signature: 'ScadaBridge.readVar(name: string): Promise<RuntimeVariable | null>',
      example: "const temp = await ScadaBridge.readVar('page.温度');",
    },
    {
      name: 'ScadaBridge.writeVar',
      summary: '写入当前页面局部变量，不走后端点位写入。',
      signature: 'ScadaBridge.writeVar(name: string, value: any): Promise<{ success: boolean, variable?: RuntimeVariable }>',
      example: "await ScadaBridge.writeVar('page.报警等级', 2);",
    },
    {
      name: 'ScadaBridge.subscribeVar',
      summary: '订阅当前页面运行时变量变化，callback 接收完整变量对象和 change。',
      signature: 'ScadaBridge.subscribeVar(name: string, callback: (variable, change) => void): () => void',
      example: "ScadaBridge.subscribeVar('page.温度', variable => console.log(variable.value));",
    },
    {
      name: 'ScadaBridge.callComponent',
      summary: '调用当前页面内其他组件注册的方法。',
      signature: 'ScadaBridge.callComponent(componentIdOrName: string, methodName: string, ...args: any[]): Promise<any>',
      example: "await ScadaBridge.callComponent('chart_temp', 'resize');",
    },
    {
      name: 'ScadaBridge.bindText',
      summary: '将变量值快捷绑定到 iframe 内的文本元素。',
      signature: 'ScadaBridge.bindText(selector: string, tagName: string, options?: { template?: string, precision?: number, fallback?: string }): () => void',
      example: "ScadaBridge.bindText('#temperature', 'temperature', { template: '{value} {unit}', precision: 1 });",
    },
    {
      name: 'ScadaBridge.bindVarText',
      summary: '将页面运行时变量快捷绑定到 iframe 内的文本元素。',
      signature: 'ScadaBridge.bindVarText(selector: string, name: string, options?: { template?: string, precision?: number, fallback?: string }): () => void',
      example: "ScadaBridge.bindVarText('#alarm', 'page.报警等级', { template: '报警等级 {value}' });",
    },
    {
      name: 'ScadaBridge.bindWriteDialog',
      summary: '点击元素后弹窗输入，并调用 writeTag 回写变量。',
      signature: 'ScadaBridge.bindWriteDialog(selector: string, tagName: string, options?: { title?: string, type?: string }): () => void',
      example: "ScadaBridge.bindWriteDialog('#setpoint', 'setpoint', { title: '写入设定值', type: 'number' });",
    },
    {
      name: 'ScadaBridge.bindVarWriteDialog',
      summary: '点击元素后弹窗输入，并写入页面运行时变量。',
      signature: 'ScadaBridge.bindVarWriteDialog(selector: string, name: string, options?: { title?: string, type?: string }): () => void',
      example: "ScadaBridge.bindVarWriteDialog('#setMode', 'page.页面模式', { title: '切换页面模式' });",
    },
    {
      name: 'ScadaBridge.query',
      summary: '执行只读数据库查询。',
      signature: 'ScadaBridge.query(sql: string, params?: any[]): Promise<any[]>',
      example: "const rows = await ScadaBridge.query('SELECT * FROM sys_ts_data WHERE tag = $1 LIMIT 10', ['A-101']);",
    },
    {
      name: 'ScadaBridge.assetUrl',
      summary: '获取已上传资产文件的访问 URL。',
      signature: 'ScadaBridge.assetUrl(assetId: string | number): string',
      example: "const url = ScadaBridge.assetUrl(42); // => '/api/assets/42/file'",
    },
  ],
  properties: [
    {
      name: 'x',
      type: 'number',
      required: true,
      summary: '组件 X 坐标。',
      usage: '画布绝对定位 left 值。',
    },
    {
      name: 'y',
      type: 'number',
      required: true,
      summary: '组件 Y 坐标。',
      usage: '画布绝对定位 top 值。',
    },
    {
      name: 'width',
      type: 'number',
      required: true,
      summary: '组件宽度。',
      usage: '建议至少 200px 以保证内容可读。',
    },
    {
      name: 'height',
      type: 'number',
      required: true,
      summary: '组件高度。',
      usage: '建议至少 150px。',
    },
    {
      name: 'htmlContent',
      type: 'string',
      required: false,
      summary: 'HTML 内容，将放入 iframe body 中。',
      usage: '仅写 body 内的 HTML 片段，不需要 <html>/<head>/<body> 标签。',
    },
    {
      name: 'cssContent',
      type: 'string',
      required: false,
      summary: 'CSS 样式代码。',
      usage: '直接写 CSS 规则，会被包裹在 <style> 标签中注入 iframe。',
    },
    {
      name: 'jsContent',
      type: 'string',
      required: false,
      summary: 'JavaScript 代码。',
      usage: '在 ScadaBridge.onReady() 回调中初始化逻辑，确保 SDK 就绪后再调用。',
      example: "ScadaBridge.onReady(() => {\n  ScadaBridge.subscribe('temperature', d => {\n    document.getElementById('value').textContent = d.value;\n  });\n});",
    },
    {
      name: 'transparent',
      type: 'boolean',
      required: false,
      summary: '是否透明背景。开启后可与下层组件叠加。',
      usage: '默认 true。关闭后 iframe 使用白色背景。',
    },
    {
      name: 'libraryAssetIds',
      type: 'string[]',
      required: false,
      summary: '引用的第三方库资产 ID 列表。',
      usage: '上传 ECharts/D3.js 等库文件后，将其资产 ID 加入此数组即可在 JS 中使用全局变量。',
    },
    {
      name: 'sandboxPermissions',
      type: 'string',
      required: false,
      summary: 'iframe sandbox 权限。',
      usage: "默认 'allow-scripts allow-modals'。如需 fetch 外部 API 可设为 'allow-scripts allow-same-origin'（降低安全隔离）。",
    },
  ],
  aiHints: [
    '生成自定义 HTML 组件时，JS 代码必须通过 ScadaBridge SDK 访问实时数据，禁止尝试 window.parent 或 document.cookie。',
    'ScadaBridge.onReady(callback) 是入口：所有 SDK 调用必须在 onReady 回调内或之后执行。',
    '简单文本显示优先用 ScadaBridge.bindText(selector, tagName, options)，避免重复手写 subscribe DOM 更新逻辑。',
    '页面局部变量使用 ScadaBridge.readVar/writeVar/subscribeVar/bindVarText/bindVarWriteDialog，不要和后端 tag 写入混用。',
    '页面局部变量名允许中文；必须以字符串传入，例如 "page.温度"，不要生成点访问表达式。',
    '简单回写优先用 ScadaBridge.bindWriteDialog(selector, tagName, options)，复杂控制再手写 writeTag。',
    '用户 HTML 不需要 <html>/<head>/<body> 包裹，直接写内容片段；CSS 和 JS 分别在独立编辑区。',
    '引用已上传的图片资产使用 ScadaBridge.assetUrl(assetId)，不要使用外部 URL 或 base64 内联。',
    '第三方库（ECharts/D3/Three.js 等）通过 libraryAssetIds 加载，用户上传离线包后选择引用，不要使用 CDN 链接。',
    '透明模式已默认开启（transparent: true），如需背景色请在 CSS 中自行设置 body 背景。',
    'subscribe 返回取消订阅函数，组件销毁前应调用以避免内存泄漏。',
  ],
};
