import type { ComponentProtocolDefinition } from '../types';

export const tableProtocol: ComponentProtocolDefinition = {
  type: 'table',
  title: 'AG Grid 表格组件',
  summary: '基于 AG Grid Community 的高性能表格物料，用于变量表、设备清单、报警记录和可编辑台账。',
  usage: [
    '表格物料使用低代码 JSON 协议映射到 AG Grid，AI 不直接生成 AG Grid 函数。',
    '列定义优先使用 columnDefs/rowData，旧 columns/dataSource 仅用于兼容历史页面。',
    '需要按钮、输入框、开关、进度条等单元格时，通过 columnDefs[].cellType 配置。',
  ],
  supportedEvents: [
    {
      key: 'onOpen',
      label: '组件打开时',
      summary: '表格初始化加载数据时执行。',
      scope: 'component',
      sharedWithAi: true,
    },
    {
      key: 'onClose',
      label: '组件关闭时',
      summary: '表格离开运行态时执行。',
      scope: 'component',
      sharedWithAi: true,
    },
    {
      key: 'onClick',
      label: '单元格按钮动作',
      summary: '当 button 类型单元格 action.type 为 script 时执行。',
      scope: 'component',
      sharedWithAi: true,
    },
  ],
  supportedMethods: [
    {
      name: 'setRows',
      summary: '运行态替换表格行数据。',
      signature: 'components.call(componentIdOrName, "setRows", rows)',
      example: 'components.call("runtime_variable_table", "setRows", [{ key: "page.温度", value: "42.5 ℃" }]);',
    },
    {
      name: 'setRowData',
      summary: '运行态替换 AG Grid 行数据。',
      signature: 'components.call(componentIdOrName, "setRowData", rows)',
      example: 'components.call("device_table", "setRowData", rows);',
    },
    {
      name: 'appendRow',
      summary: '运行态追加一行数据。',
      signature: 'components.call(componentIdOrName, "appendRow", row)',
      example: 'components.call("log_table", "appendRow", { key: Date.now(), message: "变量已变化" });',
    },
    {
      name: 'updateRow',
      summary: '按 key/id 局部更新一行。',
      signature: 'components.call(componentIdOrName, "updateRow", key, patch)',
      example: 'components.call("device_table", "updateRow", "A-101", { status: true });',
    },
    {
      name: 'deleteRow',
      summary: '按 key/id 删除一行。',
      signature: 'components.call(componentIdOrName, "deleteRow", key)',
      example: 'components.call("device_table", "deleteRow", "A-101");',
    },
    {
      name: 'setColumnDefs',
      summary: '运行态替换列定义。',
      signature: 'components.call(componentIdOrName, "setColumnDefs", columnDefs)',
      example: 'components.call("device_table", "setColumnDefs", [{ field: "name", headerName: "名称" }]);',
    },
    {
      name: 'refresh',
      summary: '强制刷新表格单元格。',
      signature: 'components.call(componentIdOrName, "refresh")',
      example: 'components.call("device_table", "refresh");',
    },
    {
      name: 'setPage',
      summary: '跳转到指定分页页码，页码从 0 开始。',
      signature: 'components.call(componentIdOrName, "setPage", page)',
      example: 'components.call("device_table", "setPage", 0);',
    },
  ],
  properties: [
    {
      name: 'x',
      type: 'number',
      required: true,
      summary: '表格 X 坐标。',
      usage: '一般与标题或筛选区左对齐。',
      example: '56',
    },
    {
      name: 'y',
      type: 'number',
      required: true,
      summary: '表格 Y 坐标。',
      usage: '应位于查询区或标题下方。',
      example: '120',
    },
    {
      name: 'width',
      type: 'number',
      required: true,
      summary: '表格宽度。',
      usage: '宽度需覆盖主要列内容。',
      example: '680',
    },
    {
      name: 'height',
      type: 'number',
      required: true,
      summary: '表格高度。',
      usage: '决定可见行数、分页条和滚动区域。',
      example: '320',
    },
    {
      name: 'gridEngine',
      type: '"ag-grid"',
      required: false,
      summary: '表格底座标识。',
      usage: '当前固定为 ag-grid，便于未来兼容其他表格引擎。',
      example: '"ag-grid"',
    },
    {
      name: 'columnDefs',
      type: 'Array<LowCodeColumn>',
      required: true,
      summary: '低代码列定义，会映射到 AG Grid columnDefs。',
      usage: '每列必须包含 field/headerName。需要交互时使用 cellType。',
      example: '[{ field: "value", headerName: "当前值", editable: true, cellType: "input" }]',
    },
    {
      name: 'rowData',
      type: 'Array<Record<string, unknown>>',
      required: true,
      summary: 'AG Grid 行数据。',
      usage: '每行建议包含稳定 key 或 id。',
      example: '[{ key: "page.温度", value: "42.5 ℃" }]',
    },
    {
      name: 'columnDefs[].cellType',
      type: '"text" | "tag" | "button" | "input" | "switch" | "progress" | "variable"',
      required: false,
      summary: '低代码单元格类型。',
      usage: 'button/input/switch/progress 等会映射为内置渲染器或编辑器。',
      example: '"button"',
    },
    {
      name: 'columnDefs[].action',
      type: 'CellAction',
      required: false,
      summary: 'button/switch 单元格动作。',
      usage: '支持 script、setPageVar、callComponent，不允许直接写函数。',
      example: '{ "type": "setPageVar", "variableName": "page.页面模式", "value": "manual" }',
    },
    {
      name: 'pagination',
      type: 'boolean | { enabled: boolean; pageSize: number; pageSizeOptions?: number[] }',
      required: false,
      summary: '分页配置。',
      usage: '大量数据建议开启分页，后续可扩展为服务端分页。',
      example: '{ "enabled": true, "pageSize": 20 }',
    },
    {
      name: 'rowSelection',
      type: '"single" | "multiple"',
      required: false,
      summary: '行选择模式。',
      usage: '需要批量操作时设为 multiple。',
      example: '"single"',
    },
    {
      name: 'theme',
      type: 'TableTheme',
      required: false,
      summary: '表格主题与隔行样式。',
      usage: '支持 compact、striped、行背景、表头颜色、边框颜色等。',
      example: '{ "compact": true, "striped": true, "oddRowBackground": "#f6f8fa" }',
    },
  ],
  aiHints: [
    '表格底座是 AG Grid Community，但 AI 只能生成低代码 JSON 协议，不要生成 AG Grid 函数或 React 组件代码。',
    '新表格统一使用 columnDefs/rowData；旧 columns/dataSource 仅做兼容，不建议继续生成。',
    '列字段使用 field/headerName，不要使用 title/dataIndex，除非是在兼容旧数据。',
    '按钮列使用 cellType="button" 和 buttonText；输入列使用 cellType="input" 或 editable=true。',
    '开关列使用 cellType="switch"；进度列使用 cellType="progress"；状态标签使用 cellType="tag"。',
    '单元格动作只能使用 action: { type: "script" | "setPageVar" | "callComponent" } 这类 JSON 描述。',
    'props.json 必须是严格 JSON，禁止在 JSON 内写 // 注释、函数、undefined 或尾逗号。',
  ],
};
