import type { ComponentProtocolDefinition } from '../types';

export const textProtocol: ComponentProtocolDefinition = {
  type: 'text',
  title: '文本组件',
  summary: '用于标题、标签、运行状态说明和工艺段标识。',
  usage: [
    '大屏标题建议使用 24 到 36 像素。',
    '状态文案建议与告警色和背景色形成强对比。',
    'AI 生成文本时，应尽量使用业务语义明确的中文短句。',
  ],
  supportedEvents: [
    {
      key: 'onOpen',
      label: '组件打开时',
      summary: '文本组件初始化显示时执行。',
      scope: 'component',
      sharedWithAi: true,
    },
    {
      key: 'onClose',
      label: '组件关闭时',
      summary: '文本组件退出显示时执行。',
      scope: 'component',
      sharedWithAi: true,
    },
  ],
  supportedMethods: [
    {
      name: 'message.success',
      summary: '在脚本中输出成功提示。',
      signature: 'message.success(content: string)',
      example: "message.success('标题已刷新');",
    },
    {
      name: 'setText',
      summary: '运行态替换文本显示内容。',
      signature: 'components.call(componentIdOrName, "setText", value)',
      example: 'components.call("text_mode", "setText", "页面模式：手动");',
    },
    {
      name: 'clearText',
      summary: '清除运行态手动文本，恢复静态 text 或 binding 显示。',
      signature: 'components.call(componentIdOrName, "clearText")',
      example: 'components.call("text_mode", "clearText");',
    },
    {
      name: 'Realtime.subscribeTag',
      summary: '运行态由组件内部使用，用于订阅后端实时变量。',
      signature: 'binding.enabled = true; binding.tagName = "temperature"',
      example: 'binding: { enabled: true, tagName: "temperature", template: "{value} {unit}" }',
    },
    {
      name: 'Realtime.writeTag',
      summary: '运行态点击文本弹窗确认后，向后端预留回写入口写入变量。',
      signature: 'writeBack.enabled = true; writeBack.tagName = "setpoint"',
      example: 'writeBack: { enabled: true, tagName: "setpoint", valueType: "number" }',
    },
    {
      name: 'PageRuntime variable binding',
      summary: '文本可绑定页面局部变量，变量对象包含 value、previousValue、quality、valueTs 和扩展字段。',
      signature: 'binding.source = "page"; binding.variableName = "page.温度"',
      example: 'binding: { enabled: true, source: "page", variableName: "page.温度", template: "{value} {unit}" }',
    },
  ],
  properties: [
    {
      name: 'x',
      type: 'number',
      required: true,
      summary: '文本 X 坐标。',
      usage: '常用于精确贴合设备图或工艺流向。',
      example: '56',
    },
    {
      name: 'y',
      type: 'number',
      required: true,
      summary: '文本 Y 坐标。',
      usage: '常与标题行或设备标签对齐。',
      example: '34',
    },
    {
      name: 'width',
      type: 'number',
      required: true,
      summary: '文本渲染区域宽度。',
      usage: '宽度不足时将影响长标题可读性。',
      example: '520',
    },
    {
      name: 'height',
      type: 'number',
      required: true,
      summary: '文本渲染区域高度。',
      usage: '应与字号和行高匹配。',
      example: '56',
    },
    {
      name: 'text',
      type: 'string',
      required: true,
      summary: '文本内容。',
      usage: '推荐直接写业务标题或状态说明。',
      example: '三号产线运行总览',
    },
    {
      name: 'color',
      type: 'string',
      required: true,
      summary: '文本颜色。',
      usage: '深色背景下推荐使用浅色字。',
      example: '#f8fafc',
    },
    {
      name: 'fontSize',
      type: 'number',
      required: true,
      summary: '字体大小。',
      usage: '标题和正文应有明显层次。',
      example: '28',
    },
    {
      name: 'binding',
      type: 'object',
      required: false,
      summary: '实时变量绑定配置。',
      usage: '开启后文本显示实时变量值，而不是静态 text。',
      example: '{ "enabled": true, "tagName": "temperature", "template": "{value} {unit}" }',
    },
    {
      name: 'writeBack',
      type: 'object',
      required: false,
      summary: '点击文本回写配置。',
      usage: '开启后预览运行态点击文本弹窗输入回写值。',
      example: '{ "enabled": true, "tagName": "setpoint", "valueType": "number" }',
    },
  ],
  aiHints: [
    'AI 生成 text 时，应优先生成业务语义化标题，而不是“新的文本组件”。',
    '当文本用作状态标签时，建议同时生成颜色字段。',
    '需要显示后端实时数据时，使用 binding 配置，不要生成轮询脚本。',
    '需要点击文本写入设定值时，使用 writeBack 配置，回写由统一实时服务处理。',
    '文本脚本直接使用 vars、components、message 和 change，不要生成 Ctx.xxx。',
    '运行态临时改文案使用 components.call(componentIdOrName, "setText", value)，恢复配置显示使用 clearText。',
    '需要读写页面局部变量时，binding/writeBack 设置 source: "page" 并使用 variableName，例如 page.温度；中文变量名必须作为字符串保存。',
  ],
};
